<?php

/**
 * @file
 * Contains commerce_vipps.module.
 */

define('COMMERCE_VIPPS_REMOTE_INITIATE', 'INITIATE');
define('COMMERCE_VIPPS_REMOTE_REGISTER', 'REGISTER');
define('COMMERCE_VIPPS_REMOTE_RESERVE', 'RESERVE');
define('COMMERCE_VIPPS_REMOTE_FAILED', 'FAILED');
define('COMMERCE_VIPPS_REMOTE_SALE', 'SALE');
define('COMMERCE_VIPPS_REMOTE_CANCEL', 'CANCEL');
define('COMMERCE_VIPPS_REMOTE_VOID', 'VOID');
define('COMMERCE_VIPPS_REMOTE_AUTOREVERSAL', 'AUTOREVERSAL');
define('COMMERCE_VIPPS_REMOTE_AUTOCANCEL', 'AUTOCANCEL');
define('COMMERCE_VIPPS_STATUS_REGISTERED', 'initiate');
const COMMERCE_VIPPS_CURRENT_TRANSACTION = 'commerce_vipps_current_transaction';

/**
 * Implements hook_theme().
 */
function commerce_vipps_theme() {
  return [
    'commerce_vipps_payment_page' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function commerce_vipps_preprocess_commerce_vipps_payment_page(&$variables) {
  $module_handler = Drupal::service('module_handler');
  $path = $module_handler->getModule('commerce_vipps')->getPath();
  $variables['module_path'] = $path;
  /** @var \Drupal\commerce_order\Entity\Order $order */
  $order = \Drupal::routeMatch()->getParameter('commerce_order');
  $variables['gateway_instance'] = $order->payment_gateway->entity->get('id');
  $variables['cancel_url'] = sprintf('/checkout/%s/payment/cancel', $order->Id());
  $variables['order_id'] = $order->id();
  $variables['payment_id'] = $order->getData(COMMERCE_VIPPS_CURRENT_TRANSACTION);
  $variables['message'] = $order->payment_gateway->entity->get('configuration')['help'];
  $variables['phone'] = $order->getBillingProfile()->{'field_phone'}->getString();
}
