commerce_payment.commerce_payment_gateway.plugin.vipps:
  type: commerce_payment_gateway_configuration
  mapping:
    client_id:
      type: string
      label: "Client ID"
    subscription_key_authorization:
      type: string
      label: "Subscription Key - Authorization"
    client_secret:
      type: string
      label: "Client Secret"
    subscription_key_payment:
      type: string
      label: "Subscription Key - Payment"
    serial_number:
      type: string
      label: "Serial Number"
    prefix:
      type: string
      label: "Prefix"
